### ISSUE TITLE
Is there a way to extend the PauseBetweenStep?

### ISSUE THREAD

**Issue by Jaykul** [StartAutomating/ShowDemo#59]
Specifically, I noticed that some of your demos on Posh are fine except that at the end, when I'm trying to appreciate _what_ the output actually looks like, it wraps and restarts too fast. E.g this one: ![Get-Member-In-Color.gif](https://github.com/StartAutomating/Posh/raw/main/Assets/Get-Member-In-Color.gif)

I don't know about you, but I need it to pause for 3 or 4 seconds more at the end, before it restarts. I think a good default might be to extend the length of the pause based on the length of the output...

**Comment by StartAutomating** [comment]
@Jaykul I think that pauses need to be broken down into multiple types, and we _might_ want to add a delay in line-by-line rendering.

I'd suggest we do a few things:

* [ ] Pause for Different Times between Documentation Steps and Code Steps
* [ ] Add a line-by-line delay in output (to control scroll speed)
* [ ] Expose -Pause(s) in a Dictionary/PSObject parameter
* [ ] Carry -Pause onto the Demo object

What do you think?

Would you like to take a quick crack?

**Comment by StartAutomating** [comment]
@Jaykul added a `-PauseBetweenLine(s)` parameter that seems like the ticket.

Feel free to try and give your $0.02
