### ISSUE TITLE
Rendering in Windows Terminal seems broken?

### ISSUE THREAD

**Issue by oising** [StartAutomating/ShowDemo#98]
I just imported the module (cloned from main) and attempted to run the stock demo. The arithmetic portion seems to be smearing things vertically - unless this is intentional?

![image](https://github.com/StartAutomating/ShowDemo/assets/1844001/66ad0d85-7a19-46a6-8244-f2cebfe45a2a)

**Comment by StartAutomating** [comment]
@oising thanks for bringing this up, will look into it and fix in an upcoming release.  Definitely not as desired.

**Comment by StartAutomating** [comment]
@oising should be fixed in the latest release.  Confirm and close at your leisure.
